import ClerkProviderClient from '@/components/ClerkProviderClient'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navigation from "@/components/navigation";
import { Toaster } from "sonner";

// Using a standard Google Fonts <link> instead of next/font to avoid Next 15 API
// mismatches in this project environment.

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // RootLayout must render <html> and <body> at the top level (server component).
  // Place client-only ClerkProvider inside <body> so Next can detect root tags.
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <meta name="naver-site-verification" content="46a4cc0ec327f438b21ecdce34934a76db0fe86f" />
      </head>
      <body>
        <ClerkProviderClient>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navigation />
            <main>
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </ClerkProviderClient>
      </body>
    </html>
  )
}
